import type { Question } from "../types";

export const q1: Question[] = [
  { id: "spicy:001", prompt: "The body part {target} is weirdly proud of is ____.", answer: "" },
  { id: "spicy:002", prompt: "{target}'s safe word would be ____.", answer: "" },
  { id: "spicy:003", prompt: "{target}'s most toxic trait in a relationship is ____.", answer: "" },
  { id: "spicy:004", prompt: "The dumbest thing {target} has done while blackout drunk is ____.", answer: "" },
  { id: "spicy:005", prompt: "{target}'s number they'd never admit out loud is ____.", answer: "" },
  { id: "spicy:006", prompt: "The kink {target} would never confess sober is ____.", answer: "" },
  { id: "spicy:007", prompt: "{target}'s walk-of-shame outfit was ____.", answer: "" },
  { id: "spicy:008", prompt: "The most embarrassing thing {target} has blurted out mid-hookup is ____.", answer: "" },
  { id: "spicy:009", prompt: "{target}'s type they're low-key ashamed of is ____.", answer: "" },
  { id: "spicy:010", prompt: "The wildest place {target} has hooked up is ____.", answer: "" },
  { id: "spicy:011", prompt: "{target} faked being tired to end a night with ____.", answer: "" },
  { id: "spicy:012", prompt: "The dating red flag {target} ignores every single time is ____.", answer: "" },
  { id: "spicy:013", prompt: "The group's guess for {target}'s body count is ____.", answer: "" },
  { id: "spicy:014", prompt: "The thing {target} does in bed that's a dealbreaker is ____.", answer: "" },
  { id: "spicy:015", prompt: "{target}'s most regrettable one-night stand involved ____.", answer: "" },
  { id: "spicy:016", prompt: "The sext {target} sent to the wrong person said ____.", answer: "" },
  { id: "spicy:017", prompt: "{target} would hook up with an ex just for ____.", answer: "" },
  { id: "spicy:018", prompt: "The most scandalous thing on {target}'s camera roll is ____.", answer: "" },
  { id: "spicy:019", prompt: "{target}'s go-to move to get someone into bed is ____.", answer: "" },
  { id: "spicy:020", prompt: "The weirdest thing that actually turns {target} on is ____.", answer: "" },
  { id: "spicy:021", prompt: "{target}'s worst booty-call decision was ____.", answer: "" },
  { id: "spicy:022", prompt: "The lie {target} tells to skip the morning-after breakfast is ____.", answer: "" },
  { id: "spicy:023", prompt: "{target} lost all dignity that one time they ____.", answer: "" },
  { id: "spicy:024", prompt: "The most people {target} has kissed in one night is ____.", answer: "" },
  { id: "spicy:025", prompt: "{target}'s dirtiest guilty pleasure is ____.", answer: "" },
  { id: "spicy:026", prompt: "The toy {target} would never admit owning is ____.", answer: "" },
  { id: "spicy:027", prompt: "{target} would strip on stage for ____.", answer: "" },
  { id: "spicy:028", prompt: "The most awkward thing {target} said during sex is ____.", answer: "" },
  { id: "spicy:029", prompt: "{target}'s ex is still traumatized by ____.", answer: "" },
  { id: "spicy:030", prompt: "The drunk text {target} sent their ex said ____.", answer: "" },
  { id: "spicy:031", prompt: "{target} would sleep with a celebrity just to ____.", answer: "" },
  { id: "spicy:032", prompt: "The pet name {target} secretly likes being called in bed is ____.", answer: "" },
  { id: "spicy:033", prompt: "{target}'s wildest hookup confession is ____.", answer: "" },
  { id: "spicy:034", prompt: "The reason {target} got kicked out of a bar is ____.", answer: "" },
  { id: "spicy:035", prompt: "{target} drunkenly threw up on ____.", answer: "" },
  { id: "spicy:036", prompt: "The most desperate thing {target} did to get laid is ____.", answer: "" },
  { id: "spicy:037", prompt: "{target}'s biggest ick that they secretly have too is ____.", answer: "" },
  { id: "spicy:038", prompt: "The thing {target} googled right after a hookup is ____.", answer: "" },
  { id: "spicy:039", prompt: "{target} would send a risky pic to ____.", answer: "" },
  { id: "spicy:040", prompt: "The most cursed thing {target} finds attractive is ____.", answer: "" },
  { id: "spicy:041", prompt: "{target}'s drunk alter ego is named ____.", answer: "" },
  { id: "spicy:042", prompt: "The worst place {target} has thrown up is ____.", answer: "" },
  { id: "spicy:043", prompt: "{target} ghosted someone entirely because of ____.", answer: "" },
  { id: "spicy:044", prompt: "The most toxic reason {target} stayed with an ex is ____.", answer: "" },
  { id: "spicy:045", prompt: "{target}'s walk of shame was witnessed by ____.", answer: "" },
];
