import type { Question } from "../types";

export const q2: Question[] = [
  { id: "spicy:046", prompt: "The thing {target} does that's secretly a thirst trap is ____.", answer: "" },
  { id: "spicy:047", prompt: "{target}'s most embarrassing turn-on is ____.", answer: "" },
  { id: "spicy:048", prompt: "The wildest lie {target} told just to get a date is ____.", answer: "" },
  { id: "spicy:049", prompt: "{target} hooked up with someone only because they ____.", answer: "" },
  { id: "spicy:050", prompt: "{target}'s most regrettable DM slide was to ____.", answer: "" },
  { id: "spicy:051", prompt: "{target}'s type is embarrassingly just ____.", answer: "" },
  { id: "spicy:052", prompt: "The reason {target}'s last hookup left early was ____.", answer: "" },
  { id: "spicy:053", prompt: "{target} would flash a stranger for ____.", answer: "" },
  { id: "spicy:054", prompt: "The most scandalous thing {target} did on vacation is ____.", answer: "" },
  { id: "spicy:055", prompt: "{target}'s drunk superpower is ____.", answer: "" },
  { id: "spicy:056", prompt: "The thing {target} pretends they're into in bed is ____.", answer: "" },
  { id: "spicy:057", prompt: "{target}'s worst hangover involved waking up next to ____.", answer: "" },
  { id: "spicy:058", prompt: "The reason {target} deleted a dating app in shame is ____.", answer: "" },
  { id: "spicy:059", prompt: "{target} would cheat at strip poker by ____.", answer: "" },
  { id: "spicy:060", prompt: "The most embarrassing noise {target} makes in bed is ____.", answer: "" },
  { id: "spicy:061", prompt: "{target}'s most shameful search after midnight is ____.", answer: "" },
  { id: "spicy:062", prompt: "The thing {target} would do for a threesome invite is ____.", answer: "" },
  { id: "spicy:063", prompt: "{target}'s drunk confession that no one forgot was ____.", answer: "" },
  { id: "spicy:064", prompt: "The worst nickname an ex ever gave {target} was ____.", answer: "" },
  { id: "spicy:065", prompt: "{target} would hook up in public at ____.", answer: "" },
  { id: "spicy:066", prompt: "The most embarrassing thing in {target}'s browser history is ____.", answer: "" },
  { id: "spicy:067", prompt: "{target}'s biggest bedroom insecurity is ____.", answer: "" },
  { id: "spicy:068", prompt: "The reason {target} was banned from an ex's family is ____.", answer: "" },
  { id: "spicy:069", prompt: "{target} drunk-dialed ____ and instantly regretted it.", answer: "" },
  { id: "spicy:070", prompt: "The most scandalous outfit {target} owns is ____.", answer: "" },
  { id: "spicy:071", prompt: "{target}'s hookup horror story involves ____.", answer: "" },
  { id: "spicy:072", prompt: "The thing {target} lies about to seem more experienced is ____.", answer: "" },
  { id: "spicy:073", prompt: "Being honest, {target} would swipe right on their ____.", answer: "" },
  { id: "spicy:074", prompt: "The most desperate booty call {target} made was to ____.", answer: "" },
  { id: "spicy:075", prompt: "{target}'s most embarrassing walk-of-shame excuse was ____.", answer: "" },
  { id: "spicy:076", prompt: "The weird thing {target} does right after sex is ____.", answer: "" },
  { id: "spicy:077", prompt: "{target}'s dating-app opener that actually worked was ____.", answer: "" },
  { id: "spicy:078", prompt: "The reason {target}'s roommate needs therapy is ____.", answer: "" },
  { id: "spicy:079", prompt: "{target} would let someone read their DMs for ____.", answer: "" },
  { id: "spicy:080", prompt: "The most toxic text {target} ever sent a partner said ____.", answer: "" },
  { id: "spicy:081", prompt: "{target}'s wildest 'never again' morning came after ____.", answer: "" },
  { id: "spicy:082", prompt: "The thing {target} still complains about their ex is ____.", answer: "" },
  { id: "spicy:083", prompt: "{target} would do body shots off ____.", answer: "" },
  { id: "spicy:084", prompt: "The most scandalous dare {target} actually completed was ____.", answer: "" },
  { id: "spicy:085", prompt: "{target}'s guilty-pleasure adult content genre is ____.", answer: "" },
  { id: "spicy:086", prompt: "The real reason {target} keeps their ex's number is ____.", answer: "" },
  { id: "spicy:087", prompt: "{target} hooked up with the last person because ____.", answer: "" },
  { id: "spicy:088", prompt: "The most embarrassing bedroom item {target} owns is ____.", answer: "" },
  { id: "spicy:089", prompt: "{target}'s type in one cursed word is ____.", answer: "" },
  { id: "spicy:090", prompt: "The drunk decision {target} defends to this day is ____.", answer: "" },
];
