import type { Question } from "../types";

export const q3: Question[] = [
  { id: "spicy:091", prompt: "{target} would sleep together on the first date if ____.", answer: "" },
  { id: "spicy:092", prompt: "The most awkward walk-in {target} ever experienced was ____.", answer: "" },
  { id: "spicy:093", prompt: "{target}'s dirtiest joke that killed the mood was ____.", answer: "" },
  { id: "spicy:094", prompt: "The reason {target} was told to keep it down is ____.", answer: "" },
  { id: "spicy:095", prompt: "{target} would send nudes if ____.", answer: "" },
  { id: "spicy:096", prompt: "The most cursed pet name {target} was called in bed is ____.", answer: "" },
  { id: "spicy:097", prompt: "{target}'s biggest romantic regret is ____.", answer: "" },
  { id: "spicy:098", prompt: "The thing {target} does to seem sober but never works is ____.", answer: "" },
  { id: "spicy:099", prompt: "{target} would hook up with a coworker named ____.", answer: "" },
  { id: "spicy:100", prompt: "The most embarrassing reason {target} got dumped is ____.", answer: "" },
  { id: "spicy:101", prompt: "{target}'s wildest club-bathroom story is ____.", answer: "" },
  { id: "spicy:102", prompt: "The lie {target} always tells about their ex is ____.", answer: "" },
  { id: "spicy:103", prompt: "{target} would ruin a friendship for a night with ____.", answer: "" },
  { id: "spicy:104", prompt: "The thing {target} did that their ex still tells people is ____.", answer: "" },
  { id: "spicy:105", prompt: "{target}'s drunk food order of shame is ____.", answer: "" },
  { id: "spicy:106", prompt: "The most public place {target} has cried over a breakup is ____.", answer: "" },
  { id: "spicy:107", prompt: "In this room, {target} would most likely kiss ____.", answer: "" },
  { id: "spicy:108", prompt: "The reason {target}'s last situationship ended is ____.", answer: "" },
  { id: "spicy:109", prompt: "{target}'s most embarrassing 'in the mood' playlist song is ____.", answer: "" },
  { id: "spicy:110", prompt: "The thing {target} secretly wants a partner to try is ____.", answer: "" },
  { id: "spicy:111", prompt: "{target} would strip for exactly ____ dollars.", answer: "" },
  { id: "spicy:112", prompt: "The most toxic thing {target} did post-breakup is ____.", answer: "" },
  { id: "spicy:113", prompt: "If {target}'s hookup left a review, it'd say ____.", answer: "" },
  { id: "spicy:114", prompt: "The real reason {target} keeps the lights off is ____.", answer: "" },
  { id: "spicy:115", prompt: "{target} would flirt their way out of ____.", answer: "" },
  { id: "spicy:116", prompt: "The most embarrassing thing {target} confessed while drunk is ____.", answer: "" },
  { id: "spicy:117", prompt: "{target}'s biggest turn-off that they're guilty of too is ____.", answer: "" },
  { id: "spicy:118", prompt: "The wildest thing {target} agreed to at 2am is ____.", answer: "" },
  { id: "spicy:119", prompt: "{target} would hook up to win a bet about ____.", answer: "" },
  { id: "spicy:120", prompt: "The most scandalous photo {target} has sent is of ____.", answer: "" },
  { id: "spicy:121", prompt: "{target}'s ex's most accurate complaint was ____.", answer: "" },
  { id: "spicy:122", prompt: "The thing {target} does when they're horny and bored is ____.", answer: "" },
  { id: "spicy:123", prompt: "{target} would date two people at once if ____.", answer: "" },
  { id: "spicy:124", prompt: "The most incriminating sound on {target}'s phone is ____.", answer: "" },
  { id: "spicy:125", prompt: "{target}'s drunk love language is ____.", answer: "" },
  { id: "spicy:126", prompt: "The reason {target} got left on read after a hookup is ____.", answer: "" },
  { id: "spicy:127", prompt: "{target} would give up sex for a whole year for ____.", answer: "" },
  { id: "spicy:128", prompt: "The most cursed thing {target} said to a date is ____.", answer: "" },
  { id: "spicy:129", prompt: "{target}'s 'I was so drunk' story ends with ____.", answer: "" },
  { id: "spicy:130", prompt: "The reason {target}'s neighbors filed a complaint is ____.", answer: "" },
  { id: "spicy:131", prompt: "{target} would let the group pick their next date at ____.", answer: "" },
  { id: "spicy:132", prompt: "The way {target} got caught lying to a partner was ____.", answer: "" },
  { id: "spicy:133", prompt: "{target}'s toxic dating pattern is always ____.", answer: "" },
  { id: "spicy:134", prompt: "The thing {target} would never do sober but always drunk is ____.", answer: "" },
  { id: "spicy:135", prompt: "{target}'s most scandalous 'it was just once' story is ____.", answer: "" },
];
