import type { Question } from "../types";

export const q1: Question[] = [
  { id: "truth:001", prompt: "{target}'s most useless talent is ____.", answer: "" },
  { id: "truth:002", prompt: "If {target} were a kitchen appliance, they'd be a ____.", answer: "" },
  { id: "truth:003", prompt: "The weirdest thing {target} has ever eaten is ____.", answer: "" },
  { id: "truth:004", prompt: "The celebrity {target} would ghost everyone for is ____.", answer: "" },
  { id: "truth:005", prompt: "{target} will be famous one day for ____.", answer: "" },
  { id: "truth:006", prompt: "The one chore {target} secretly enjoys is ____.", answer: "" },
  { id: "truth:007", prompt: "{target}'s go-to karaoke song is ____.", answer: "" },
  { id: "truth:008", prompt: "The app {target} spends way too much time on is ____.", answer: "" },
  { id: "truth:009", prompt: "If {target} won the lottery, the first thing they'd buy is ____.", answer: "" },
  { id: "truth:010", prompt: "{target}'s hidden talent nobody knows about is ____.", answer: "" },
  { id: "truth:011", prompt: "The snack {target} could eat every single day is ____.", answer: "" },
  { id: "truth:012", prompt: "{target}'s most irrational fear is ____.", answer: "" },
  { id: "truth:013", prompt: "The last thing {target} googled was ____.", answer: "" },
  { id: "truth:014", prompt: "If {target} were an animal, they'd be a ____.", answer: "" },
  { id: "truth:015", prompt: "{target}'s guilty-pleasure TV show is ____.", answer: "" },
  { id: "truth:016", prompt: "The weirdest habit {target} has is ____.", answer: "" },
  { id: "truth:017", prompt: "{target} would survive a zombie apocalypse for about ____.", answer: "" },
  { id: "truth:018", prompt: "The one food {target} refuses to eat is ____.", answer: "" },
  { id: "truth:019", prompt: "If {target} started a band, it would be called ____.", answer: "" },
  { id: "truth:020", prompt: "{target}'s dream vacation destination is ____.", answer: "" },
  { id: "truth:021", prompt: "The chore {target} avoids at all costs is ____.", answer: "" },
  { id: "truth:022", prompt: "{target}'s childhood nickname was ____.", answer: "" },
  { id: "truth:023", prompt: "The thing {target} is weirdly competitive about is ____.", answer: "" },
  { id: "truth:024", prompt: "If {target} could have any superpower, they'd pick ____.", answer: "" },
  { id: "truth:025", prompt: "{target}'s most-used emoji is ____.", answer: "" },
  { id: "truth:026", prompt: "The movie {target} has secretly watched too many times is ____.", answer: "" },
  { id: "truth:027", prompt: "{target} would trade their phone for ____.", answer: "" },
  { id: "truth:028", prompt: "The strangest job {target} would actually be good at is ____.", answer: "" },
  { id: "truth:029", prompt: "{target}'s comfort food after a bad day is ____.", answer: "" },
  { id: "truth:030", prompt: "If {target} were a pizza topping, they'd be ____.", answer: "" },
  { id: "truth:031", prompt: "The one thing {target} always forgets is ____.", answer: "" },
  { id: "truth:032", prompt: "{target}'s spirit animal is a ____.", answer: "" },
  { id: "truth:033", prompt: "The item in {target}'s fridge that's been there too long is ____.", answer: "" },
  { id: "truth:034", prompt: "If {target} ran for president, their slogan would be ____.", answer: "" },
  { id: "truth:035", prompt: "{target}'s biggest pet peeve is ____.", answer: "" },
  { id: "truth:036", prompt: "The thing {target} would grab first in a fire is ____.", answer: "" },
  { id: "truth:037", prompt: "{target} secretly wishes they were better at ____.", answer: "" },
  { id: "truth:038", prompt: "The weirdest thing in {target}'s search history is ____.", answer: "" },
  { id: "truth:039", prompt: "If {target} were a weather forecast, they'd be ____.", answer: "" },
  { id: "truth:040", prompt: "{target}'s ideal way to spend a Friday night is ____.", answer: "" },
  { id: "truth:041", prompt: "The one skill {target} brags about is ____.", answer: "" },
];
