import type { Question } from "../types";

export const q2: Question[] = [
  { id: "truth:042", prompt: "The thing that instantly ruins {target}'s day is ____.", answer: "" },
  { id: "truth:043", prompt: "If {target} opened a restaurant, it would serve ____.", answer: "" },
  { id: "truth:044", prompt: "{target}'s most embarrassing school memory involves ____.", answer: "" },
  { id: "truth:045", prompt: "The gadget {target} bought and never used is ____.", answer: "" },
  { id: "truth:046", prompt: "{target} would rather give up ____ than their morning coffee.", answer: "" },
  { id: "truth:047", prompt: "The song {target} is embarrassed to love is ____.", answer: "" },
  { id: "truth:048", prompt: "If {target} were a cartoon character, they'd be ____.", answer: "" },
  { id: "truth:049", prompt: "{target}'s worst fashion phase involved ____.", answer: "" },
  { id: "truth:050", prompt: "The thing {target} pretends to understand but doesn't is ____.", answer: "" },
  { id: "truth:051", prompt: "{target}'s dream superpower for everyday life is ____.", answer: "" },
  { id: "truth:052", prompt: "The weirdest gift {target} has ever received is ____.", answer: "" },
  { id: "truth:053", prompt: "If {target} could time travel, they'd go to ____.", answer: "" },
  { id: "truth:054", prompt: "{target}'s go-to excuse for being late is ____.", answer: "" },
  { id: "truth:055", prompt: "The one thing {target} hoards for no reason is ____.", answer: "" },
  { id: "truth:056", prompt: "{target} secretly judges people who ____.", answer: "" },
  { id: "truth:057", prompt: "The reality show {target} would actually win is ____.", answer: "" },
  { id: "truth:058", prompt: "If {target} had a warning label, it would say ____.", answer: "" },
  { id: "truth:059", prompt: "{target}'s most-repeated catchphrase is ____.", answer: "" },
  { id: "truth:060", prompt: "The thing {target} does when nobody's watching is ____.", answer: "" },
  { id: "truth:061", prompt: "{target} would fail a survival show because of ____.", answer: "" },
  { id: "truth:062", prompt: "The subject {target} could talk about for hours is ____.", answer: "" },
  { id: "truth:063", prompt: "If {target} were a holiday, they'd be ____.", answer: "" },
  { id: "truth:064", prompt: "{target}'s most impulsive purchase was ____.", answer: "" },
  { id: "truth:065", prompt: "The one movie {target} always falls asleep during is ____.", answer: "" },
  { id: "truth:066", prompt: "{target}'s dream pet would be a ____.", answer: "" },
  { id: "truth:067", prompt: "The thing {target} always overpacks is ____.", answer: "" },
  { id: "truth:068", prompt: "If {target} wrote a memoir, the title would be ____.", answer: "" },
  { id: "truth:069", prompt: "{target}'s hidden obsession is ____.", answer: "" },
  { id: "truth:070", prompt: "The chore {target} would pay someone else to do is ____.", answer: "" },
  { id: "truth:071", prompt: "{target}'s worst cooking disaster involved ____.", answer: "" },
  { id: "truth:072", prompt: "The thing {target} is weirdly good at is ____.", answer: "" },
  { id: "truth:073", prompt: "If {target} were a board game, they'd be ____.", answer: "" },
  { id: "truth:074", prompt: "{target}'s least favorite word is ____.", answer: "" },
  { id: "truth:075", prompt: "The one thing {target} refuses to share is ____.", answer: "" },
  { id: "truth:076", prompt: "{target} would win an award for ____.", answer: "" },
  { id: "truth:077", prompt: "The strangest thing {target} finds relaxing is ____.", answer: "" },
  { id: "truth:078", prompt: "If {target} could master any instrument, it would be the ____.", answer: "" },
  { id: "truth:079", prompt: "{target}'s go-to comfort movie is ____.", answer: "" },
  { id: "truth:080", prompt: "The weirdest place {target} has fallen asleep is ____.", answer: "" },
  { id: "truth:081", prompt: "{target}'s biggest online-shopping weakness is ____.", answer: "" },
  { id: "truth:082", prompt: "The thing {target} always says they'll do but never does is ____.", answer: "" },
];
