import type { Question } from "../types";

export const q3: Question[] = [
  { id: "truth:083", prompt: "If {target} were a sandwich, they'd be a ____.", answer: "" },
  { id: "truth:084", prompt: "{target}'s most useless piece of trivia is ____.", answer: "" },
  { id: "truth:085", prompt: "The thing {target} secretly loves about mornings is ____.", answer: "" },
  { id: "truth:086", prompt: "{target} would survive on a desert island with only ____.", answer: "" },
  { id: "truth:087", prompt: "The one emoji that describes {target} is ____.", answer: "" },
  { id: "truth:088", prompt: "If {target} were a scent, they'd smell like ____.", answer: "" },
  { id: "truth:089", prompt: "{target}'s worst haircut looked like ____.", answer: "" },
  { id: "truth:090", prompt: "The thing {target} always loses is ____.", answer: "" },
  { id: "truth:091", prompt: "{target}'s dream dinner guest would be ____.", answer: "" },
  { id: "truth:092", prompt: "The weirdest thing {target} collects is ____.", answer: "" },
  { id: "truth:093", prompt: "If {target} were a vegetable, they'd be a ____.", answer: "" },
  { id: "truth:094", prompt: "{target}'s most-played song on repeat is ____.", answer: "" },
  { id: "truth:095", prompt: "The thing {target} is oddly protective of is ____.", answer: "" },
  { id: "truth:096", prompt: "{target} would rather be stuck in an elevator with ____.", answer: "" },
  { id: "truth:097", prompt: "The one talent {target} wishes they had is ____.", answer: "" },
  { id: "truth:098", prompt: "If {target} were a dessert, they'd be ____.", answer: "" },
  { id: "truth:099", prompt: "{target}'s go-to dance move is ____.", answer: "" },
  { id: "truth:100", prompt: "The thing {target} always burns while cooking is ____.", answer: "" },
  { id: "truth:101", prompt: "{target}'s childhood dream job was ____.", answer: "" },
  { id: "truth:102", prompt: "The weirdest advice {target} lives by is ____.", answer: "" },
  { id: "truth:103", prompt: "If {target} were a color, they'd be ____.", answer: "" },
  { id: "truth:104", prompt: "{target}'s most embarrassing autocorrect fail was ____.", answer: "" },
  { id: "truth:105", prompt: "The thing {target} refuses to throw away is ____.", answer: "" },
  { id: "truth:106", prompt: "{target} would start a riot if you took away their ____.", answer: "" },
  { id: "truth:107", prompt: "The one show {target} has rewatched too many times is ____.", answer: "" },
  { id: "truth:108", prompt: "If {target} were a mythical creature, they'd be a ____.", answer: "" },
  { id: "truth:109", prompt: "{target}'s secret superpower at parties is ____.", answer: "" },
  { id: "truth:110", prompt: "The thing {target} does to procrastinate is ____.", answer: "" },
  { id: "truth:111", prompt: "{target}'s ideal breakfast is ____.", answer: "" },
  { id: "truth:112", prompt: "The weirdest compliment {target} has received is ____.", answer: "" },
  { id: "truth:113", prompt: "If {target} ran a museum, it would display ____.", answer: "" },
  { id: "truth:114", prompt: "{target}'s most dramatic overreaction was about ____.", answer: "" },
  { id: "truth:115", prompt: "The one thing {target} can't say no to is ____.", answer: "" },
  { id: "truth:116", prompt: "{target} would be terrible at the job of ____.", answer: "" },
  { id: "truth:117", prompt: "The strangest thing {target} believes is ____.", answer: "" },
  { id: "truth:118", prompt: "If {target} were a type of weather, they'd be ____.", answer: "" },
  { id: "truth:119", prompt: "{target}'s go-to karaoke backup song is ____.", answer: "" },
  { id: "truth:120", prompt: "The thing {target} always cries at is ____.", answer: "" },
  { id: "truth:121", prompt: "{target}'s most-worn item of clothing is ____.", answer: "" },
  { id: "truth:122", prompt: "The weirdest thing {target} has said in their sleep is ____.", answer: "" },
  { id: "truth:123", prompt: "If {target} were a superhero, their weakness would be ____.", answer: "" },
];
