import type { Question } from "../types";

export const q4: Question[] = [
  { id: "truth:124", prompt: "{target}'s dream road trip destination is ____.", answer: "" },
  { id: "truth:125", prompt: "The one food {target} could never live without is ____.", answer: "" },
  { id: "truth:126", prompt: "{target}'s most irrational purchase regret is ____.", answer: "" },
  { id: "truth:127", prompt: "The thing {target} pretends to like but secretly hates is ____.", answer: "" },
  { id: "truth:128", prompt: "If {target} were a fast-food chain, they'd be ____.", answer: "" },
  { id: "truth:129", prompt: "{target}'s biggest phone-battery drainer is ____.", answer: "" },
  { id: "truth:130", prompt: "The chore {target} is weirdly proud of doing well is ____.", answer: "" },
  { id: "truth:131", prompt: "{target} would win a gold medal in the sport of ____.", answer: "" },
  { id: "truth:132", prompt: "The one thing {target} always forgets to buy is ____.", answer: "" },
  { id: "truth:133", prompt: "If {target} had a theme song, it would be ____.", answer: "" },
  { id: "truth:134", prompt: "{target}'s worst travel mishap involved ____.", answer: "" },
  { id: "truth:135", prompt: "The weirdest thing {target} keeps in their bag is ____.", answer: "" },
  { id: "truth:136", prompt: "{target}'s go-to comfort snack is ____.", answer: "" },
  { id: "truth:137", prompt: "The thing {target} would ban if they ran the world is ____.", answer: "" },
  { id: "truth:138", prompt: "If {target} were a houseplant, they'd be a ____.", answer: "" },
  { id: "truth:139", prompt: "{target}'s most embarrassing childhood obsession was ____.", answer: "" },
  { id: "truth:140", prompt: "The one gadget {target} can't live without is ____.", answer: "" },
  { id: "truth:141", prompt: "{target} would happily give up ____ for a week of naps.", answer: "" },
  { id: "truth:142", prompt: "The strangest talent {target}'s family has is ____.", answer: "" },
  { id: "truth:143", prompt: "If {target} were a breakfast cereal, they'd be ____.", answer: "" },
  { id: "truth:144", prompt: "{target}'s biggest kitchen fail was ____.", answer: "" },
  { id: "truth:145", prompt: "The thing {target} always double-checks is ____.", answer: "" },
  { id: "truth:146", prompt: "{target}'s dream superpower for winning arguments is ____.", answer: "" },
  { id: "truth:147", prompt: "The one movie quote {target} overuses is ____.", answer: "" },
  { id: "truth:148", prompt: "If {target} were a season, they'd be ____.", answer: "" },
  { id: "truth:149", prompt: "{target}'s weirdest morning ritual is ____.", answer: "" },
  { id: "truth:150", prompt: "The thing {target} secretly wants to be famous for is ____.", answer: "" },
  { id: "truth:151", prompt: "{target} would rather delete every app except ____.", answer: "" },
  { id: "truth:152", prompt: "The most childish thing {target} still enjoys is ____.", answer: "" },
  { id: "truth:153", prompt: "If {target} were a road sign, they'd say ____.", answer: "" },
  { id: "truth:154", prompt: "{target}'s go-to karaoke duet partner would be ____.", answer: "" },
  { id: "truth:155", prompt: "The thing {target} always over-explains is ____.", answer: "" },
  { id: "truth:156", prompt: "{target}'s most-visited website is ____.", answer: "" },
  { id: "truth:157", prompt: "The weirdest food combo {target} enjoys is ____.", answer: "" },
  { id: "truth:158", prompt: "If {target} were a piece of furniture, they'd be a ____.", answer: "" },
  { id: "truth:159", prompt: "{target}'s biggest guilty-pleasure purchase is ____.", answer: "" },
  { id: "truth:160", prompt: "The one thing {target} would save from their childhood is ____.", answer: "" },
  { id: "truth:161", prompt: "{target} would be the first to panic if ____.", answer: "" },
  { id: "truth:162", prompt: "The strangest thing {target} has ever named is ____.", answer: "" },
  { id: "truth:163", prompt: "If {target} were a superhero sidekick, their name would be ____.", answer: "" },
  { id: "truth:164", prompt: "{target}'s dream last meal would be ____.", answer: "" },
];
