import type { Question } from "../types";

export const questions: Question[] = [
  { id: "headlines:046", prompt: "At a long-running American contest, teams build catapults and air cannons to hurl ____ as far as they can.", answer: "pumpkins", alts: ["pumpkin"], note: "\"Punkin Chunkin\" machines have flung pumpkins over half a mile." },
  { id: "headlines:047", prompt: "Finland hosts a straight-faced world championship where performers compete at playing an invisible ____.", answer: "guitar", note: "Air Guitar World Championships judge stage presence and \"airness.\"" },
  { id: "headlines:048", prompt: "In 1962 a contagious outbreak forced a Tanzania school to shut down because students could not stop ____.", answer: "laughing", alts: ["laughter"], note: "The mass psychogenic \"laughter epidemic\" spread to nearby villages." },
  { id: "headlines:049", prompt: "In 1518 in Strasbourg, dozens of people reportedly could not stop ____ for days in a mysterious plague.", answer: "dancing", alts: ["dance"], note: "Some danced themselves to exhaustion in the \"dancing plague.\"" },
  { id: "headlines:050", prompt: "Two rival medieval Italian cities went to war in 1325 over a stolen wooden ____.", answer: "bucket", alts: ["pail"], note: "Modena's raiders grabbed a bucket from Bologna; the bucket is still displayed." },
  { id: "headlines:051", prompt: "In 1859 the US and Britain nearly went to war on a disputed island over the shooting of a single ____.", answer: "pig", note: "The only casualty of the \"Pig War\" was the pig itself." },
  { id: "headlines:052", prompt: "In 1876 witnesses in Bath County, Kentucky, reported flakes of ____ falling from a clear sky.", answer: "meat", alts: ["flesh"], note: "The \"Kentucky meat shower\" was later blamed on vultures vomiting in flight." },
  { id: "headlines:053", prompt: "In documented \"animal rain\" events, waterspouts have scooped up and dropped live ____ onto startled towns.", answer: "fish", alts: ["fishes", "frogs"], note: "Towns from Wales to Honduras report raining fish and frogs." },
  { id: "headlines:054", prompt: "There is a genuine world championship judging elaborately styled and sculpted ____.", answer: "beards", alts: ["beard", "moustaches", "facial hair"], note: "The World Beard and Moustache Championships has categories like \"freestyle.\"" },
  { id: "headlines:055", prompt: "At English \"worm charming\" contests, players drum and vibrate the ground to coax ____ up to the surface.", answer: "worms", alts: ["earthworms", "worm"], note: "A 10-year-old once charmed over 500 worms out of a plot in half an hour." },
  { id: "headlines:056", prompt: "Since 1947 a Florida roadside park has staged live underwater shows starring performers dressed as ____.", answer: "mermaids", alts: ["mermaid"], note: "Weeki Wachee's \"mermaids\" breathe from hidden air hoses in a spring." },
  { id: "headlines:057", prompt: "In Florida, one man secretly and single-handedly carved and stacked a mysterious castle out of tons of ____.", answer: "coral", alts: ["coral rock", "limestone"], note: "How he moved the heavy Coral Castle blocks alone remains debated." },
  { id: "headlines:058", prompt: "A French entertainer known as \"Mr. Eat-All\" ate metal for shows and reportedly consumed an entire ____.", answer: "airplane", alts: ["plane", "Cessna", "aircraft"], note: "Michel Lotito ground a Cessna into filings and ate it over two years." },
  { id: "headlines:059", prompt: "In 1974 a Frenchman was arrested after secretly walking a ____ strung between New York's Twin Towers.", answer: "tightrope", alts: ["wire", "high wire", "highwire"], note: "Philippe Petit crossed 1,300 feet up, eight times, before police caught him." },
  { id: "headlines:060", prompt: "In 2012 an Austrian daredevil broke the sound barrier with his body by skydiving from the edge of ____.", answer: "space", alts: ["the stratosphere", "stratosphere"], note: "Felix Baumgartner jumped from a balloon at about 24 miles up." },
];
