import type { Question } from "../types";

export const questions: Question[] = [
  { id: "headlines:091", prompt: "A chapel in the Czech Republic is decorated with chandeliers and art crafted entirely from human ____.", answer: "bones", alts: ["skulls", "skeletons", "bone"], note: "The Sedlec Ossuary arranges the remains of tens of thousands of people." },
  { id: "headlines:092", prompt: "A rifle heiress spent decades building a California mansion crammed with staircases and doors that lead ____.", answer: "nowhere", note: "Legend says she kept building to confuse the ghosts of gun victims." },
  { id: "headlines:093", prompt: "In Nebraska, a man built a full-size replica of Stonehenge entirely out of vintage ____.", answer: "cars", alts: ["automobiles", "car"], note: "\"Carhenge\" uses 39 gray-painted vehicles planted in a circle." },
  { id: "headlines:094", prompt: "A museum near Boston is devoted entirely to collecting and displaying spectacularly ____ art.", answer: "bad", alts: ["terrible", "awful"], note: "The Museum of Bad Art celebrates work \"too bad to be ignored.\"" },
  { id: "headlines:095", prompt: "Florence, Italy hosts a brutal historic sport mixing soccer, rugby and bare-knuckle ____.", answer: "fighting", alts: ["boxing", "brawling"], note: "Calcio storico players wear Renaissance costumes and few rules apply." },
  { id: "headlines:096", prompt: "In an English town's centuries-old street football game, the two goals sit about ____ miles apart.", answer: "three", alts: ["3"], note: "Ashbourne's Royal Shrovetide match turns the whole town into a pitch." },
  { id: "headlines:097", prompt: "Turkey's national sport is a form of wrestling in which competitors slather themselves head to toe in ____.", answer: "oil", alts: ["olive oil"], note: "Kirkpinar oil wrestling dates back over 650 years." },
  { id: "headlines:098", prompt: "Twice each summer, jockeys race bareback ____ at breakneck speed around the medieval square of Siena.", answer: "horses", alts: ["horse"], note: "The Palio di Siena lasts about 90 seconds of chaos." },
  { id: "headlines:099", prompt: "The original 1920 \"Ponzi scheme\" promised huge returns by supposedly trading in international postal ____.", answer: "stamps", alts: ["coupons", "reply coupons"], note: "Charles Ponzi just paid old investors with new investors' cash." },
  { id: "headlines:100", prompt: "A notorious New York con man repeatedly \"sold\" the ____ Bridge to gullible newcomers.", answer: "Brooklyn", alts: ["brooklyn"], note: "George C. Parker \"sold\" landmarks he didn't own, sometimes twice a week." },
  { id: "headlines:101", prompt: "A famous impostor faked his way into jobs as a prison warden, monk and Navy surgeon, even performing real ____.", answer: "surgery", alts: ["operations", "surgeries"], note: "Ferdinand Demara operated on sailors using a textbook, and they lived." },
  { id: "headlines:102", prompt: "A famous Australian science experiment running since 1927 measures how a blob of ____ drips once a decade.", answer: "pitch", alts: ["tar", "bitumen"], note: "The tar-like pitch looks solid but flows; few have ever seen a drop fall." },
  { id: "headlines:103", prompt: "In 1975 an American got rich briefly by selling ordinary ____ in gift boxes as low-maintenance pets.", answer: "rocks", alts: ["stones", "rock"], note: "The \"Pet Rock\" came with a straight-faced care-and-training manual." },
  { id: "headlines:104", prompt: "An 18th-century chess-playing \"automaton\" called the Turk beat challengers thanks to a hidden ____.", answer: "person", alts: ["man", "human", "chess master"], note: "A skilled player crouched inside the cabinet working the machine." },
  { id: "headlines:105", prompt: "A Wyoming taxidermist invented a beloved mythical critter by grafting antlers onto a stuffed ____.", answer: "jackrabbit", alts: ["rabbit", "hare"], note: "The \"jackalope\" is now Wyoming's tongue-in-cheek official mythical creature." },
];
