import type { Question } from "../types";

export const questions: Question[] = [
  { id: "headlines:106", prompt: "Australians love to prank tourists with tales of a vicious predatory ____ that drops onto victims from trees.", answer: "koala", alts: ["drop bear", "bear"], note: "The \"drop bear\" is a made-up killer cousin of the cuddly koala." },
  { id: "headlines:107", prompt: "The most famous 1934 photo of the Loch Ness Monster was later confessed to be a model built on a toy ____.", answer: "submarine", alts: ["toy submarine", "sub"], note: "The \"Surgeon's Photograph\" was a hoax with a sculpted head on a toy sub." },
  { id: "headlines:108", prompt: "A livestock-draining monster of Latin American legend is named for its supposed taste for ____ blood.", answer: "goat", alts: ["goats"], note: "\"Chupacabra\" literally means \"goat-sucker\" in Spanish." },
  { id: "headlines:109", prompt: "A teenage American fugitive stole cars and boats, and even taught himself to fly stolen ____, often while barefoot.", answer: "planes", alts: ["airplanes", "aircraft", "plane"], note: "The \"Barefoot Bandit\" crash-landed planes he'd never been trained to fly." },
  { id: "headlines:110", prompt: "A young American con man in the 1960s cashed millions in bad checks while impersonating an airline ____.", answer: "pilot", alts: ["co-pilot"], note: "Frank Abagnale also posed as a doctor and a lawyer before age 21." },
  { id: "headlines:111", prompt: "In 2016 a British public poll to name a polar research ____ overwhelmingly chose \"Boaty McBoatface.\"", answer: "ship", alts: ["vessel", "boat"], note: "Officials overrode the vote; the name went to a mini submarine instead." },
  { id: "headlines:112", prompt: "In 1630s Holland, speculation went so wild that a single ____ bulb could cost more than a canal house.", answer: "tulip", alts: ["tulips"], note: "\"Tulip mania\" is often cited as one of history's first market bubbles." },
  { id: "headlines:113", prompt: "A Virginia urban legend tells of an axe-wielding man dressed in a ____ costume who attacks from an overpass.", answer: "bunny", alts: ["rabbit"], note: "The \"Bunny Man\" tale is tied to a real spooky railway bridge near Fairfax." },
  { id: "headlines:114", prompt: "In 1912 a celebrated \"missing link\" fossil was exposed decades later as a human skull fused with an ape ____.", answer: "jaw", alts: ["jawbone", "orangutan jaw"], note: "\"Piltdown Man\" fooled scientists for 40 years before the fake was caught." },
  { id: "headlines:115", prompt: "Showman P. T. Barnum drew paying crowds with a \"mermaid\" that was a monkey's torso sewn to a ____ tail.", answer: "fish", alts: ["fish tail"], note: "The grim \"Fiji mermaid\" was a taxidermy mashup, not a sea maiden." },
  { id: "headlines:116", prompt: "A craze swept the 1970s in which people would suddenly sprint ____ through games, awards shows and campuses.", answer: "naked", alts: ["nude"], note: "One famous streaker crossed the stage at the 1974 Academy Awards.", adult: true },
  { id: "headlines:117", prompt: "In the 1990s otherwise sensible adults hoarded, insured and even divorced over small collectible plush ____.", answer: "animals", alts: ["toys", "Beanie Babies", "beanie babies"], note: "The \"Beanie Baby\" bubble had couples dividing toys in court." },
  { id: "headlines:118", prompt: "The Czech city of Prague is famous for political disputes settled by tossing officials out a ____.", answer: "window", alts: ["windows"], note: "Prague's \"defenestrations\" helped spark real wars; some victims survived a dung heap." },
  { id: "headlines:119", prompt: "In an 1810 London prank, a man mailed hoax orders that flooded one house with hundreds of unwanted ____.", answer: "deliveries", alts: ["tradesmen", "visitors", "tradespeople"], note: "The Berners Street Hoax summoned coal, cakes, doctors and even the mayor." },
  { id: "headlines:120", prompt: "In the Texas Panhandle, an eccentric millionaire half-buried ten ____ nose-down in a field for the public to spray-paint.", answer: "Cadillacs", alts: ["cars", "Cadillac", "cadillacs"], note: "Cadillac Ranch near Amarillo is repainted by visitors almost daily." },
];
