import type { Question } from "../types";

export const questions: Question[] = [
  { id: "wtf:092", prompt: "At the 2010 MTV Video Music Awards, Lady Gaga wore a dress made of ____.", answer: "meat", note: "It was later preserved and treated as beef jerky." },
  { id: "wtf:093", prompt: "Angelina Jolie and Billy Bob Thornton wore lockets holding each other's ____.", answer: "blood", note: "They wore lockets with a drop of blood; Thornton says full 'vials' were an exaggeration." },
  { id: "wtf:094", prompt: "Actor Tom Hanks is famous for collecting vintage ____.", answer: "typewriters", note: "He owns well over a hundred working machines." },
  { id: "wtf:095", prompt: "Artist Salvador Dali once walked an ____ on a leash in Paris.", answer: "anteater", note: "He also kept an ocelot as a household pet." },
  { id: "wtf:096", prompt: "Poet Lord Byron kept a pet ____ in his Cambridge dorm.", answer: "bear", note: "Dorm rules banned dogs, but said nothing about bears." },
  { id: "wtf:097", prompt: "Actor Nicolas Cage had to return a stolen ____ skull he had bought.", answer: "dinosaur", note: "The skull had been smuggled out of Mongolia." },
  { id: "wtf:098", prompt: "Michael Jackson had a famous pet ____ named Bubbles.", answer: "chimpanzee", alts: ["chimp"], note: "Bubbles now lives at a Florida ape sanctuary." },
  { id: "wtf:099", prompt: "Boxer Mike Tyson once kept pet ____ at his mansion.", answer: "tigers", alts: ["tiger"], note: "He owned several Bengal tigers for years." },
  { id: "wtf:100", prompt: "Rocker Keith Richards claimed he once snorted his late father's ____.", answer: "ashes", note: "He later said the shocking line was mostly a joke.", adult: true },
  { id: "wtf:101", prompt: "In 2013 Germany confiscated Justin Bieber's pet ____.", answer: "monkey", note: "The capuchin ended up in a German zoo." },
  { id: "wtf:102", prompt: "Listerine was originally sold as a surgical antiseptic and a ____ cleaner.", answer: "floor", note: "It was marketed for all sorts of uses before mouthwash." },
  { id: "wtf:103", prompt: "Until 1948, the soft drink 7 Up contained the mood-stabilizing drug ____.", answer: "lithium", note: "The metal was quietly dropped from the recipe." },
  { id: "wtf:104", prompt: "Coca-Cola invented the orange soda Fanta during WWII in ____.", answer: "Nazi Germany", alts: ["Germany"], note: "A bottler improvised it from leftover ingredients." },
  { id: "wtf:105", prompt: "Dr. John Harvey Kellogg promoted corn flakes partly to curb ____.", answer: "masturbation", alts: ["sexual urges"], note: "He believed bland food would tame the urge.", adult: true },
  { id: "wtf:106", prompt: "Before settling on 'Amazon,' Jeff Bezos nearly named the company ____.", answer: "Relentless", alts: ["Cadabra"], note: "The domain relentless.com still redirects to Amazon." },
  { id: "wtf:107", prompt: "Google was originally named ____ before its founders renamed it.", answer: "BackRub", note: "The final name plays on the number 'googol.'" },
  { id: "wtf:108", prompt: "Pepsi-Cola was first sold under the name ____.", answer: "Brad's Drink", note: "It was named after its inventor, Caleb Bradham." },
  { id: "wtf:109", prompt: "The coffee chain Starbucks is named after a character in the novel ____.", answer: "Moby-Dick", alts: ["Moby Dick"], note: "Starbuck was the first mate on the whaling ship." },
  { id: "wtf:110", prompt: "The sportswear brand Reebok is named after an African ____.", answer: "antelope", note: "The grey rhebok is a small African antelope." },
  { id: "wtf:111", prompt: "Before building supercars, Lamborghini made ____.", answer: "tractors", note: "The founder ran a successful tractor business first." },
  { id: "wtf:112", prompt: "The ice cream name 'Haagen-Dazs' was invented in New York and means ____.", answer: "nothing", note: "The founders faked a Danish-sounding name for appeal." },
  { id: "wtf:113", prompt: "The brand Nike is named after the Greek goddess of ____.", answer: "victory", note: "Nike personified triumph in Greek myth." },
  { id: "wtf:114", prompt: "WD-40 got its name because it was the ____th attempt at Water Displacement.", answer: "40", alts: ["fortieth"], note: "The first 39 rust-fighting formulas failed." },
  { id: "wtf:115", prompt: "Sylvester Graham invented the graham cracker to help suppress ____.", answer: "lust", alts: ["sexual urges", "desire"], note: "He preached a bland diet to tame the passions.", adult: true },
  { id: "wtf:116", prompt: "Vaseline's inventor claimed to eat a spoonful of the jelly every ____.", answer: "day", note: "Robert Chesebrough swore it kept him healthy for decades." },
];
