import type { Question } from "../types";

export const q1: Question[] = [
  { id: "unhinged:001", prompt: "{target}'s villain origin story starts with ____.", answer: "" },
  { id: "unhinged:002", prompt: "If {target} was arrested tonight, the charge would be ____.", answer: "" },
  { id: "unhinged:003", prompt: "The thing {target} would sell their soul for is ____.", answer: "" },
  { id: "unhinged:004", prompt: "{target}'s FBI agent's biggest concern is ____.", answer: "" },
  { id: "unhinged:005", prompt: "At 3am, {target} is probably googling ____.", answer: "" },
  { id: "unhinged:006", prompt: "A cult led by {target} would worship ____.", answer: "" },
  { id: "unhinged:007", prompt: "{target} would be the first to die in a horror movie because ____.", answer: "" },
  { id: "unhinged:008", prompt: "{target}'s Roman Empire is ____.", answer: "" },
  { id: "unhinged:009", prompt: "The TED talk {target} would give is called ____.", answer: "" },
  { id: "unhinged:010", prompt: "If {target}'s life was a Netflix documentary, the title would be ____.", answer: "" },
  { id: "unhinged:011", prompt: "{target} would start a war over ____.", answer: "" },
  { id: "unhinged:012", prompt: "The last straw before {target} finally snaps is ____.", answer: "" },
  { id: "unhinged:013", prompt: "{target}'s secret evil laugh is triggered by ____.", answer: "" },
  { id: "unhinged:014", prompt: "If {target} ruled the world, their day-one law would be ____.", answer: "" },
  { id: "unhinged:015", prompt: "The conspiracy theory {target} secretly believes is ____.", answer: "" },
  { id: "unhinged:016", prompt: "{target} would fake their own death to avoid ____.", answer: "" },
  { id: "unhinged:017", prompt: "The weapon {target} would grab in a bar fight is ____.", answer: "" },
  { id: "unhinged:018", prompt: "{target}'s wanted poster would say ____.", answer: "" },
  { id: "unhinged:019", prompt: "If {target} were a warning sign, it would read ____.", answer: "" },
  { id: "unhinged:020", prompt: "The reason {target} is on a government watchlist is ____.", answer: "" },
  { id: "unhinged:021", prompt: "{target} would haunt people after death by ____.", answer: "" },
  { id: "unhinged:022", prompt: "The forbidden snack {target} guards with their life is ____.", answer: "" },
  { id: "unhinged:023", prompt: "{target}'s toxic trait dressed up as a personality is ____.", answer: "" },
  { id: "unhinged:024", prompt: "If {target} joined a heist crew, their role would be ____.", answer: "" },
  { id: "unhinged:025", prompt: "The thing {target} whispers to themselves in the mirror is ____.", answer: "" },
  { id: "unhinged:026", prompt: "{target}'s emotional support object is ____.", answer: "" },
  { id: "unhinged:027", prompt: "If {target} were a cryptid, they'd be spotted doing ____.", answer: "" },
  { id: "unhinged:028", prompt: "The unhinged group-chat message {target} would send is ____.", answer: "" },
  { id: "unhinged:029", prompt: "{target} would absolutely lose it if you touched their ____.", answer: "" },
  { id: "unhinged:030", prompt: "The petty revenge {target} is fully capable of is ____.", answer: "" },
  { id: "unhinged:031", prompt: "{target}'s alter ego's name is ____.", answer: "" },
  { id: "unhinged:032", prompt: "If {target} snapped, the town would remember it as ____.", answer: "" },
  { id: "unhinged:033", prompt: "The cursed item {target} would buy at a garage sale is ____.", answer: "" },
  { id: "unhinged:034", prompt: "{target}'s final words would probably be ____.", answer: "" },
  { id: "unhinged:035", prompt: "The thing {target} does that would concern a therapist is ____.", answer: "" },
  { id: "unhinged:036", prompt: "If {target} were a boss battle, their weakness would be ____.", answer: "" },
  { id: "unhinged:037", prompt: "{target} would trade a kidney for ____.", answer: "" },
  { id: "unhinged:038", prompt: "The most feral thing {target} has done for food is ____.", answer: "" },
  { id: "unhinged:039", prompt: "{target}'s red-flag first-date confession would be ____.", answer: "" },
  { id: "unhinged:040", prompt: "If {target} had a mugshot, they'd be holding ____.", answer: "" },
  { id: "unhinged:041", prompt: "The apocalypse would end faster if {target} ran ____.", answer: "" },
  { id: "unhinged:042", prompt: "{target} secretly rehearses arguments about ____.", answer: "" },
  { id: "unhinged:043", prompt: "The unhinged hill {target} would die on is ____.", answer: "" },
  { id: "unhinged:044", prompt: "If {target} were a haunted house, the ghost would just be ____.", answer: "" },
  { id: "unhinged:045", prompt: "{target}'s villain monologue would be about ____.", answer: "" },
  { id: "unhinged:046", prompt: "The thing {target} would smuggle across a border is ____.", answer: "" },
  { id: "unhinged:047", prompt: "{target} would survive a cult by becoming the ____.", answer: "" },
  { id: "unhinged:048", prompt: "The weird flex {target} won't shut up about is ____.", answer: "" },
  { id: "unhinged:049", prompt: "If {target} were a medication warning label, it'd say ____.", answer: "" },
  { id: "unhinged:050", prompt: "{target}'s chaotic 2am plan involves ____.", answer: "" },
  { id: "unhinged:051", prompt: "The reason {target} got banned from a place is ____.", answer: "" },
  { id: "unhinged:052", prompt: "{target} would win a shady Nobel Prize for ____.", answer: "" },
  { id: "unhinged:053", prompt: "The thing {target} hoards like a dragon is ____.", answer: "" },
  { id: "unhinged:054", prompt: "If {target} were an action figure, the accessory would be ____.", answer: "" },
  { id: "unhinged:055", prompt: "{target}'s most unhinged shower thought is ____.", answer: "" },
  { id: "unhinged:056", prompt: "The most illegal thing {target} would do for a snack is ____.", answer: "" },
];
