import type { Question } from "../types";

export const q2: Question[] = [
  { id: "unhinged:057", prompt: "{target} would ghost their own funeral for ____.", answer: "" },
  { id: "unhinged:058", prompt: "The reason aliens would abduct {target} is ____.", answer: "" },
  { id: "unhinged:059", prompt: "{target}'s search bar's most shameful autocomplete is ____.", answer: "" },
  { id: "unhinged:060", prompt: "If {target} started a riot, it would be over ____.", answer: "" },
  { id: "unhinged:061", prompt: "The thing {target} would do if the cameras stopped for an hour is ____.", answer: "" },
  { id: "unhinged:062", prompt: "{target}'s spirit demon feeds on ____.", answer: "" },
  { id: "unhinged:063", prompt: "If {target} were a horror-movie killer, their gimmick would be ____.", answer: "" },
  { id: "unhinged:064", prompt: "The unhinged advice {target} gives at 3am is ____.", answer: "" },
  { id: "unhinged:065", prompt: "{target} would fistfight a stranger over ____.", answer: "" },
  { id: "unhinged:066", prompt: "The thing hidden in {target}'s glovebox is ____.", answer: "" },
  { id: "unhinged:067", prompt: "{target}'s villain lair would be decorated with ____.", answer: "" },
  { id: "unhinged:068", prompt: "If {target} were a warning email, the subject line would be ____.", answer: "" },
  { id: "unhinged:069", prompt: "The thing {target} does that screams 'unwell' is ____.", answer: "" },
  { id: "unhinged:070", prompt: "{target} would feed the group to a monster to save ____.", answer: "" },
  { id: "unhinged:071", prompt: "The reason {target} would be kicked out of a library is ____.", answer: "" },
  { id: "unhinged:072", prompt: "{target}'s unhinged coping mechanism is ____.", answer: "" },
  { id: "unhinged:073", prompt: "If {target} were a scented candle, the scent would be ____.", answer: "" },
  { id: "unhinged:074", prompt: "The thing {target} would do with unlimited power is ____.", answer: "" },
  { id: "unhinged:075", prompt: "{target}'s most dramatic villain exit would involve ____.", answer: "" },
  { id: "unhinged:076", prompt: "The forbidden knowledge {target} secretly possesses is ____.", answer: "" },
  { id: "unhinged:077", prompt: "{target} would trade their firstborn for ____.", answer: "" },
  { id: "unhinged:078", prompt: "The reason {target} can never run for office is ____.", answer: "" },
  { id: "unhinged:079", prompt: "{target}'s therapist quietly quit because of ____.", answer: "" },
  { id: "unhinged:080", prompt: "If {target} were a Pokémon, their special attack would be ____.", answer: "" },
  { id: "unhinged:081", prompt: "The chaotic-evil thing {target} does in traffic is ____.", answer: "" },
  { id: "unhinged:082", prompt: "{target}'s doomsday bunker would be stocked with ____.", answer: "" },
  { id: "unhinged:083", prompt: "The thing {target} screams into the void is ____.", answer: "" },
  { id: "unhinged:084", prompt: "If {target} got a warning tattoo, it would say ____.", answer: "" },
  { id: "unhinged:085", prompt: "{target} would fake an accent to escape ____.", answer: "" },
  { id: "unhinged:086", prompt: "The most unhinged item in {target}'s cart right now is ____.", answer: "" },
  { id: "unhinged:087", prompt: "{target}'s inner monologue during small talk is ____.", answer: "" },
  { id: "unhinged:088", prompt: "The reason a psychic refuses to read {target} is ____.", answer: "" },
  { id: "unhinged:089", prompt: "{target} would burn a bridge just to ____.", answer: "" },
  { id: "unhinged:090", prompt: "If {target} were a haunted doll, they'd whisper ____.", answer: "" },
  { id: "unhinged:091", prompt: "The thing {target} would do if consequences didn't exist is ____.", answer: "" },
  { id: "unhinged:092", prompt: "{target}'s villain theme song would be ____.", answer: "" },
  { id: "unhinged:093", prompt: "The reason {target} would survive a purge is ____.", answer: "" },
  { id: "unhinged:094", prompt: "{target} would commit tax fraud for ____.", answer: "" },
  { id: "unhinged:095", prompt: "The weirdest thing {target} has narrated out loud is ____.", answer: "" },
  { id: "unhinged:096", prompt: "If {target} were a scam, the pitch would be ____.", answer: "" },
  { id: "unhinged:097", prompt: "{target}'s unhinged reaction to being left on read is ____.", answer: "" },
  { id: "unhinged:098", prompt: "The thing {target} would resurrect from the dead is ____.", answer: "" },
  { id: "unhinged:099", prompt: "{target} would start a doomsday cult to avoid ____.", answer: "" },
  { id: "unhinged:100", prompt: "The reason {target} isn't allowed near a karaoke machine is ____.", answer: "" },
  { id: "unhinged:101", prompt: "{target}'s most chaotic 'good idea at the time' was ____.", answer: "" },
  { id: "unhinged:102", prompt: "If {target} led a forbidden ritual, the offering would be ____.", answer: "" },
  { id: "unhinged:103", prompt: "The thing {target} would do to win a staring contest is ____.", answer: "" },
  { id: "unhinged:104", prompt: "{target}'s unhinged dream last night was probably about ____.", answer: "" },
  { id: "unhinged:105", prompt: "{target}'s aunty would gossip that they're secretly ____.", answer: "" },
  { id: "unhinged:106", prompt: "The reason {target}'s shaadi keeps getting delayed is ____.", answer: "" },
  { id: "unhinged:107", prompt: "{target} would fight the entire family WhatsApp group over ____.", answer: "" },
  { id: "unhinged:108", prompt: "The jugaad {target} is weirdly proud of is ____.", answer: "" },
  { id: "unhinged:109", prompt: "{target}'s Roman Empire, but it's a cricket match, is ____.", answer: "" },
  { id: "unhinged:110", prompt: "The thing {target} would do to dodge a rishta meeting is ____.", answer: "" },
  { id: "unhinged:111", prompt: "Relatives compare {target}'s villain era to ____.", answer: "" },
  { id: "unhinged:112", prompt: "If {target}'s life were a Bollywood movie, it'd be titled ____.", answer: "" },
];
