import type { Question } from "../types";

export const q3: Question[] = [
  { id: "unhinged:113", prompt: "{target} would start a chai-based cult worshipping ____.", answer: "" },
  { id: "unhinged:114", prompt: "The reason {target}'s mom is disappointed today is ____.", answer: "" },
  { id: "unhinged:115", prompt: "{target} would haggle to the death over ____.", answer: "" },
  { id: "unhinged:116", prompt: "The auntie-approved rumor about {target} is ____.", answer: "" },
  { id: "unhinged:117", prompt: "{target} would trade their soul to skip ____.", answer: "" },
  { id: "unhinged:118", prompt: "The most cursed thing in {target}'s phone gallery is ____.", answer: "" },
  { id: "unhinged:119", prompt: "{target}'s unhinged villain catchphrase is ____.", answer: "" },
  { id: "unhinged:120", prompt: "If {target} were a natural disaster, they'd be ____.", answer: "" },
  { id: "unhinged:121", prompt: "The thing {target} would do for the last slice of pizza is ____.", answer: "" },
  { id: "unhinged:122", prompt: "{target}'s secret lair password is ____.", answer: "" },
  { id: "unhinged:123", prompt: "The reason {target} would be exiled from the group chat is ____.", answer: "" },
  { id: "unhinged:124", prompt: "{target} would fake amnesia to get out of ____.", answer: "" },
  { id: "unhinged:125", prompt: "The most deranged thing {target} finds relaxing is ____.", answer: "" },
  { id: "unhinged:126", prompt: "If {target} were an urban legend, the warning would be ____.", answer: "" },
  { id: "unhinged:127", prompt: "{target}'s chaotic contribution to any plan is ____.", answer: "" },
  { id: "unhinged:128", prompt: "The thing {target} would do if invisible for a day is ____.", answer: "" },
  { id: "unhinged:129", prompt: "{target}'s unhinged 'trust me' plan is ____.", answer: "" },
  { id: "unhinged:130", prompt: "The reason {target} got a strongly-worded email is ____.", answer: "" },
  { id: "unhinged:131", prompt: "{target} would betray the whole group for ____.", answer: "" },
  { id: "unhinged:132", prompt: "The forbidden food combo {target} defends is ____.", answer: "" },
  { id: "unhinged:133", prompt: "If {target} were a horror sound effect, they'd be ____.", answer: "" },
  { id: "unhinged:134", prompt: "{target}'s most feral craving at midnight is ____.", answer: "" },
  { id: "unhinged:135", prompt: "The thing {target} would do to be the main character is ____.", answer: "" },
  { id: "unhinged:136", prompt: "{target}'s villain redemption arc would start with ____.", answer: "" },
  { id: "unhinged:137", prompt: "The reason {target} got muted in the family group chat is ____.", answer: "" },
  { id: "unhinged:138", prompt: "{target} would sell the group's secrets for ____.", answer: "" },
  { id: "unhinged:139", prompt: "The unhinged reason {target} was late is ____.", answer: "" },
  { id: "unhinged:140", prompt: "If {target} were a GPS warning, it'd say ____.", answer: "" },
  { id: "unhinged:141", prompt: "{target}'s doomsday prediction is that ____ ends the world.", answer: "" },
  { id: "unhinged:142", prompt: "The thing {target} would do the second they won a fight is ____.", answer: "" },
  { id: "unhinged:143", prompt: "{target}'s chaotic energy peaks whenever ____.", answer: "" },
  { id: "unhinged:144", prompt: "The reason {target} would be picked last for the apocalypse team is ____.", answer: "" },
  { id: "unhinged:145", prompt: "{target} would trade a friend for ____.", answer: "" },
  { id: "unhinged:146", prompt: "The most unhinged text {target} sent stone-cold sober is ____.", answer: "" },
  { id: "unhinged:147", prompt: "If {target} were a forbidden spell, it would summon ____.", answer: "" },
  { id: "unhinged:148", prompt: "{target}'s secret side hustle would be ____.", answer: "" },
  { id: "unhinged:149", prompt: "The reason {target} would end up on a reality show is ____.", answer: "" },
  { id: "unhinged:150", prompt: "{target} would riot in the streets if they banned ____.", answer: "" },
  { id: "unhinged:151", prompt: "The cursed talent {target} secretly has is ____.", answer: "" },
  { id: "unhinged:152", prompt: "{target}'s unhinged life motto is ____.", answer: "" },
  { id: "unhinged:153", prompt: "The thing {target} would do to a slow walker is ____.", answer: "" },
  { id: "unhinged:154", prompt: "If {target} were a haunted appliance, they'd malfunction by ____.", answer: "" },
  { id: "unhinged:155", prompt: "{target}'s most chaotic group-trip decision was ____.", answer: "" },
  { id: "unhinged:156", prompt: "The reason {target} would survive on pure spite is ____.", answer: "" },
  { id: "unhinged:157", prompt: "{target}'s 'log kya kahenge' moment was ____.", answer: "" },
  { id: "unhinged:158", prompt: "The reason {target}'s relatives think they've 'changed' is ____.", answer: "" },
  { id: "unhinged:159", prompt: "{target} would start a WhatsApp forward war about ____.", answer: "" },
  { id: "unhinged:160", prompt: "The desi snack {target} would commit crimes for is ____.", answer: "" },
  { id: "unhinged:161", prompt: "The aunty network flagged {target} for ____.", answer: "" },
  { id: "unhinged:162", prompt: "The reason {target} dodges every family function is ____.", answer: "" },
  { id: "unhinged:163", prompt: "{target} would argue with a rickshaw driver over ____.", answer: "" },
  { id: "unhinged:164", prompt: "The Bollywood villain {target} secretly channels is ____.", answer: "" },
  { id: "unhinged:165", prompt: "{target}'s most unhinged cricket-match behavior is ____.", answer: "" },
  { id: "unhinged:166", prompt: "The thing {target}'s mom brags about that isn't even true is ____.", answer: "" },
  { id: "unhinged:167", prompt: "{target} would fake a bad network to escape ____.", answer: "" },
];
