import type { Question } from "../types";

export const questions: Question[] = [
  { id: "facts:001", prompt: "A group of flamingos is called a ____.", answer: "flamboyance", note: "A fitting name for a flock of bright pink birds." },
  { id: "facts:002", prompt: "Hippos can't ____.", answer: "jump", note: "They can gallop but never get all four feet off the ground." },
  { id: "facts:003", prompt: "A group of crows is called a ____.", answer: "murder", alts: ["a murder"], note: "One of the eeriest collective nouns in English." },
  { id: "facts:004", prompt: "An octopus has ____ hearts.", answer: "three", alts: ["3"], note: "Two pump blood to the gills, one to the rest of the body." },
  { id: "facts:005", prompt: "An octopus has ____ blood.", answer: "blue", note: "It uses copper-based hemocyanin instead of iron." },
  { id: "facts:006", prompt: "A shrimp's heart is located in its ____.", answer: "head", note: "Its organs are packed up near the head." },
  { id: "facts:007", prompt: "Starfish do not have a ____.", answer: "brain", note: "They rely on a simple nerve net instead." },
  { id: "facts:008", prompt: "A group of owls is called a ____.", answer: "parliament", note: "Popularized by the Narnia books." },
  { id: "facts:009", prompt: "Wombat poop is shaped like a ____.", answer: "cube", alts: ["cubes"], note: "Their intestines mold droppings into near-cubes." },
  { id: "facts:010", prompt: "A group of jellyfish is called a ____.", answer: "smack", note: "Also called a bloom or a swarm." },
  { id: "facts:011", prompt: "Butterflies taste with their ____.", answer: "feet", note: "Foot receptors help them find the right plants." },
  { id: "facts:012", prompt: "A group of pandas is called an ____.", answer: "embarrassment", note: "An embarrassment of pandas is a real term." },
  { id: "facts:013", prompt: "Adult elephants are physically unable to ____.", answer: "jump", note: "They always keep at least one foot on the ground." },
  { id: "facts:014", prompt: "A group of rhinos is called a ____.", answer: "crash", note: "Fitting for a charging herd of two-ton animals." },
  { id: "facts:015", prompt: "Among seahorses, the ____ carries the babies.", answer: "male", alts: ["father", "males"], note: "Males brood the eggs and give birth." },
  { id: "facts:016", prompt: "A group of ferrets is called a ____.", answer: "business", note: "Sometimes spelled busyness." },
  { id: "facts:017", prompt: "Sea otters hold ____ while sleeping.", answer: "hands", alts: ["paws"], note: "They link paws so they don't drift apart." },
  { id: "facts:018", prompt: "Tigers have striped ____, not just striped fur.", answer: "skin", note: "The stripe pattern is on their skin too." },
  { id: "facts:019", prompt: "A group of porcupines is called a ____.", answer: "prickle", note: "An apt name for a cluster of spiky rodents." },
  { id: "facts:020", prompt: "Cats can't taste ____.", answer: "sweetness", alts: ["sweet", "sugar"], note: "They lack a working sweet taste receptor." },
  { id: "facts:021", prompt: "A blue whale's heart is roughly the size of a ____.", answer: "car", alts: ["small car"], note: "It weighs around 400 pounds." },
  { id: "facts:022", prompt: "Snails have thousands of ____.", answer: "teeth", note: "Their tongue-like radula is covered in tiny teeth." },
  { id: "facts:023", prompt: "An ostrich's eye is bigger than its ____.", answer: "brain", alts: ["brains"], note: "It has the largest eye of any land animal." },
  { id: "facts:024", prompt: "A group of giraffes is called a ____.", answer: "tower", note: "A tower of giraffes -- of course." },
  { id: "facts:025", prompt: "Male penguins often propose with a ____.", answer: "pebble", alts: ["rock", "stone"], note: "Gentoo penguins offer a smooth stone." },
  { id: "facts:026", prompt: "Axolotls can regrow their ____.", answer: "limbs", alts: ["legs", "leg"], note: "They can also regrow parts of the heart and brain." },
  { id: "facts:027", prompt: "A group of ravens is called an ____.", answer: "unkindness", note: "An unkindness, or a conspiracy, of ravens." },
  { id: "facts:028", prompt: "Goats have rectangular ____.", answer: "pupils", note: "The wide shape gives them a broad field of view." },
];
