import type { Question } from "../types";

export const questions: Question[] = [
  { id: "facts:029", prompt: "A group of kangaroos is called a ____.", answer: "mob", note: "Also called a troop or a court." },
  { id: "facts:030", prompt: "A group of zebras is called a ____.", answer: "dazzle", note: "Their stripes really do dazzle predators." },
  { id: "facts:031", prompt: "Polar bears have ____ skin.", answer: "black", note: "Their fur is actually translucent, not white." },
  { id: "facts:032", prompt: "Snakes smell with their ____.", answer: "tongue", alts: ["tongues"], note: "The forked tongue collects scent for a special organ." },
  { id: "facts:033", prompt: "A group of lemurs is called a ____.", answer: "conspiracy", note: "A conspiracy of lemurs is the real term." },
  { id: "facts:034", prompt: "A narwhal's tusk is actually a ____.", answer: "tooth", alts: ["teeth"], note: "It's an overgrown canine packed with nerves." },
  { id: "facts:035", prompt: "Sharks are older than ____.", answer: "trees", note: "Sharks predate trees by tens of millions of years." },
  { id: "facts:036", prompt: "Some reindeer eyes turn ____ in winter.", answer: "blue", note: "Arctic reindeer eyes shift from gold to blue." },
  { id: "facts:037", prompt: "An adult human body has ____ bones.", answer: "206", note: "Babies start with far more that fuse over time." },
  { id: "facts:038", prompt: "Babies are born with about ____ bones.", answer: "300", note: "Many fuse together as they grow." },
  { id: "facts:039", prompt: "The strongest bone in the body is the ____.", answer: "femur", alts: ["thigh bone", "thighbone"], note: "It supports many times your body weight." },
  { id: "facts:040", prompt: "The smallest bone in your body is in your ____.", answer: "ear", note: "The stapes is smaller than a grain of rice." },
  { id: "facts:041", prompt: "The only bone not connected to another bone is the ____.", answer: "hyoid", note: "This throat bone supports the tongue." },
  { id: "facts:042", prompt: "A full set of adult teeth numbers ____.", answer: "32", note: "That includes the four wisdom teeth." },
  { id: "facts:043", prompt: "The largest organ in the human body is the ____.", answer: "skin", note: "It can cover about 20 square feet in an adult." },
  { id: "facts:044", prompt: "Your left lung is smaller to make room for your ____.", answer: "heart", note: "The heart tilts slightly to the left." },
  { id: "facts:045", prompt: "Goosebumps are a leftover reflex from having ____.", answer: "fur", alts: ["body hair", "hair"], note: "Fluffed fur once made ancestors look bigger." },
  { id: "facts:046", prompt: "Fingernails grow faster than ____.", answer: "toenails", note: "Roughly twice as fast, in fact." },
  { id: "facts:047", prompt: "Stomach acid is strong enough to dissolve ____.", answer: "metal", note: "A mucus lining keeps it from digesting your stomach." },
  { id: "facts:048", prompt: "The one organ that can't feel pain is the ____.", answer: "brain", note: "It has no pain receptors of its own." },
  { id: "facts:049", prompt: "Your corneas get oxygen directly from the ____.", answer: "air", note: "They have no blood vessels of their own." },
  { id: "facts:050", prompt: "The human tongue holds about ____ taste buds.", answer: "10,000", alts: ["10000", "ten thousand"], note: "They're replaced roughly every two weeks." },
  { id: "facts:051", prompt: "The only muscle attached at just one end is the ____.", answer: "tongue", note: "It's a bundle of muscles anchored at the back." },
  { id: "facts:052", prompt: "Your heart is about the size of your ____.", answer: "fist", note: "It beats around 100,000 times a day." },
  { id: "facts:053", prompt: "The hardest substance in the human body is tooth ____.", answer: "enamel", note: "It's harder than bone but can't repair itself." },
  { id: "facts:054", prompt: "Humans have the same number of neck bones as a ____.", answer: "giraffe", note: "Almost all mammals have exactly seven neck vertebrae." },
  { id: "facts:055", prompt: "The sense most tightly linked to memory is ____.", answer: "smell", note: "Scent connects directly to memory centers." },
  { id: "facts:056", prompt: "A red blood cell lives about ____ days.", answer: "120", note: "Then it's recycled by the spleen and liver." },
];
