import type { Question } from "../types";

export const questions: Question[] = [
  { id: "facts:057", prompt: "Humans are the only animals with a true ____.", answer: "chin", note: "No other species, not even other apes, has one." },
  { id: "facts:058", prompt: "You blink roughly ____ times per minute.", answer: "15", alts: ["20", "15-20"], note: "That adds up to millions of blinks a year." },
  { id: "facts:059", prompt: "A single day on ____ is longer than its whole year.", answer: "Venus", note: "It rotates slower than it orbits the Sun." },
  { id: "facts:060", prompt: "The hottest planet in our solar system is ____.", answer: "Venus", note: "Its thick atmosphere traps more heat than Mercury." },
  { id: "facts:061", prompt: "The only planet that rotates on its side is ____.", answer: "Uranus", note: "It's tipped nearly 98 degrees." },
  { id: "facts:062", prompt: "____ is light enough that it would float in water.", answer: "Saturn", note: "Its average density is less than water's." },
  { id: "facts:063", prompt: "A teaspoon of a ____ star would weigh billions of tons.", answer: "neutron", note: "Neutron stars are almost unimaginably dense." },
  { id: "facts:064", prompt: "It may rain ____ on Jupiter and Saturn.", answer: "diamonds", note: "Intense pressure can turn carbon into diamond." },
  { id: "facts:065", prompt: "The Sun makes up about ____% of the solar system's mass.", answer: "99", alts: ["99.8", "99.8%"], note: "Everything else is a rounding error." },
  { id: "facts:066", prompt: "Space is completely ____.", answer: "silent", note: "There's no air to carry sound waves." },
  { id: "facts:067", prompt: "The largest volcano in the solar system is on ____.", answer: "Mars", note: "Olympus Mons is about three times Everest's height." },
  { id: "facts:068", prompt: "About ____ million Earths could fit inside the Sun.", answer: "1", alts: ["one", "1.3"], note: "Roughly 1.3 million, actually." },
  { id: "facts:069", prompt: "The Moon is slowly drifting ____ from Earth.", answer: "away", note: "About 3.8 centimeters farther each year." },
  { id: "facts:070", prompt: "A year on ____ lasts just 88 Earth days.", answer: "Mercury", note: "It's the fastest planet around the Sun." },
  { id: "facts:071", prompt: "Footprints on the ____ could last millions of years.", answer: "Moon", note: "No wind or water exists there to erase them." },
  { id: "facts:072", prompt: "There are more stars in the universe than grains of ____ on Earth.", answer: "sand", alts: ["sand grains"], note: "By most estimates, vastly more." },
  { id: "facts:073", prompt: "The most abundant element in the universe is ____.", answer: "hydrogen", note: "It makes up about three-quarters of normal matter." },
  { id: "facts:074", prompt: "Sunlight takes about ____ minutes to reach Earth.", answer: "8", alts: ["eight", "8.3"], note: "You always see the Sun as it was minutes ago." },
  { id: "facts:075", prompt: "The Sun is classified as a yellow ____.", answer: "dwarf", note: "A yellow dwarf, or G-type main-sequence star." },
  { id: "facts:076", prompt: "The largest desert on Earth is ____.", answer: "Antarctica", note: "A desert is defined by low precipitation, not heat." },
  { id: "facts:077", prompt: "The driest place on Earth is the ____ Desert.", answer: "Atacama", note: "Some spots have had no recorded rain for years." },
  { id: "facts:078", prompt: "Russia spans ____ time zones.", answer: "11", note: "More than any other country." },
  { id: "facts:079", prompt: "You float easily in the ____ Sea.", answer: "Dead", note: "Its extreme saltiness makes you buoyant." },
  { id: "facts:080", prompt: "The smallest country in the world is ____.", answer: "Vatican City", alts: ["the Vatican", "Vatican"], note: "It covers only about 44 hectares." },
  { id: "facts:081", prompt: "The largest ocean on Earth is the ____.", answer: "Pacific", note: "It holds more than half of Earth's free water." },
  { id: "facts:082", prompt: "The only country that is also a continent is ____.", answer: "Australia", note: "It's both a country and a continental landmass." },
  { id: "facts:083", prompt: "Thousands of years ago the Sahara was ____.", answer: "green", note: "It was once dotted with lakes and grassland." },
  { id: "facts:084", prompt: "Istanbul sits on two ____.", answer: "continents", note: "It straddles Europe and Asia across the Bosphorus." },
];
