import type { Question } from "../types";

export const questions: Question[] = [
  { id: "facts:085", prompt: "Canada holds more ____ than the rest of the world combined.", answer: "lakes", note: "It has over half of the planet's natural lakes." },
  { id: "facts:086", prompt: "Saudi Arabia has no naturally occurring ____.", answer: "rivers", alts: ["river"], note: "It relies on aquifers and desalination." },
  { id: "facts:087", prompt: "The world's tallest waterfall is ____ Falls.", answer: "Angel", note: "It plunges over 3,200 feet in Venezuela." },
  { id: "facts:088", prompt: "Measured base to peak, the tallest mountain is ____.", answer: "Mauna Kea", note: "Most of it is hidden underwater." },
  { id: "facts:089", prompt: "The point farthest from Earth's center is Mount ____.", answer: "Chimborazo", note: "Earth's bulge gives it the edge over Everest." },
  { id: "facts:090", prompt: "Honey never ____.", answer: "spoils", alts: ["goes bad", "expires"], note: "Sealed honey has been found edible after 3,000 years." },
  { id: "facts:091", prompt: "Botanically, bananas are ____.", answer: "berries", alts: ["a berry", "berry"], note: "But strawberries technically are not." },
  { id: "facts:092", prompt: "The most expensive spice by weight is ____.", answer: "saffron", note: "It takes thousands of flowers to make one ounce." },
  { id: "facts:093", prompt: "Peanuts are not true nuts, they are ____.", answer: "legumes", alts: ["a legume", "legume"], note: "They're related to beans and lentils." },
  { id: "facts:094", prompt: "The earliest cultivated carrots were ____.", answer: "purple", note: "Orange carrots came much later." },
  { id: "facts:095", prompt: "Apples belong to the ____ family.", answer: "rose", note: "So do pears, cherries, and almonds." },
  { id: "facts:096", prompt: "In large amounts, nutmeg is ____.", answer: "toxic", alts: ["poisonous"], note: "It contains myristicin, harmful in big doses." },
  { id: "facts:097", prompt: "A cashew grows attached to a cashew ____.", answer: "apple", note: "The nut hangs beneath a fleshy fruit." },
  { id: "facts:098", prompt: "A cucumber is about ____% water.", answer: "96", alts: ["95"], note: "That's why it's so crisp and cooling." },
  { id: "facts:099", prompt: "Ketchup was once sold as ____.", answer: "medicine", note: "In the 1830s it was marketed for indigestion." },
  { id: "facts:100", prompt: "Rhubarb leaves are ____.", answer: "poisonous", alts: ["toxic"], note: "They contain high levels of oxalic acid." },
  { id: "facts:101", prompt: "Botanically speaking, a tomato is a ____.", answer: "fruit", note: "Specifically a berry, though we cook it as a veggie." },
  { id: "facts:102", prompt: "White chocolate contains no cocoa ____.", answer: "solids", note: "It's made from cocoa butter, sugar, and milk." },
  { id: "facts:103", prompt: "Almonds are closely related to ____.", answer: "peaches", alts: ["peach"], note: "Both are stone fruits in the rose family." },
  { id: "facts:104", prompt: "A pineapple takes about ____ years to grow.", answer: "two", alts: ["2", "2-3"], note: "Each plant produces just one pineapple at a time." },
  { id: "facts:105", prompt: "The Aztecs used ____ beans as money.", answer: "cacao", alts: ["cocoa"], note: "Chocolate was literally currency." },
  { id: "facts:106", prompt: "The heat in chili peppers comes from ____.", answer: "capsaicin", note: "It tricks pain receptors into sensing heat." },
  { id: "facts:107", prompt: "The only metal that is liquid at room temperature is ____.", answer: "mercury", note: "It stays liquid until about minus 39 Celsius." },
  { id: "facts:108", prompt: "The hardest natural substance is ____.", answer: "diamond", note: "It's made of pure carbon under great pressure." },
  { id: "facts:109", prompt: "Water is unusual because it expands when it ____.", answer: "freezes", note: "That's why ice floats." },
  { id: "facts:110", prompt: "A lightning bolt is about ____ times hotter than the Sun's surface.", answer: "five", alts: ["5"], note: "It can reach around 30,000 Celsius." },
  { id: "facts:111", prompt: "The most abundant gas in Earth's atmosphere is ____.", answer: "nitrogen", note: "It makes up about 78 percent of the air." },
  { id: "facts:112", prompt: "Sound travels faster in ____ than in air.", answer: "water", note: "About four times faster, in fact." },
];
