import type { Question } from "../types";

export const questions: Question[] = [
  { id: "facts:113", prompt: "Absolute zero is about ____ degrees Celsius.", answer: "-273", alts: ["minus 273", "-273.15"], note: "The coldest anything can theoretically get." },
  { id: "facts:114", prompt: "Breathing helium makes your voice sound ____.", answer: "higher", note: "Sound moves faster through helium than air." },
  { id: "facts:115", prompt: "Hot water freezing faster than cold is the ____ effect.", answer: "Mpemba", note: "Named after a student who noticed it in ice cream." },
  { id: "facts:116", prompt: "Glass is made mainly from ____.", answer: "sand", note: "Melted silica sand is its key ingredient." },
  { id: "facts:117", prompt: "Most metals ____ when heated.", answer: "expand", note: "Their atoms vibrate and push farther apart." },
  { id: "facts:118", prompt: "Light travels at about ____ kilometers per second.", answer: "300,000", alts: ["300000", "299,792"], note: "Nothing with mass can match it." },
  { id: "facts:119", prompt: "Lightning strikes Earth roughly ____ times every second.", answer: "100", alts: ["hundred"], note: "That's millions of strikes each day." },
  { id: "facts:120", prompt: "The most common letter in English is ____.", answer: "E", alts: ["e"], note: "It appears in about one of every eight letters." },
  { id: "facts:121", prompt: "The dot over a lowercase i or j is called a ____.", answer: "tittle", note: "Yes, that tiny dot has its own name." },
  { id: "facts:122", prompt: "The only common English word ending in -mt is ____.", answer: "dreamt", note: "Along with its cousin undreamt." },
  { id: "facts:123", prompt: "A word that reads the same backward and forward is a ____.", answer: "palindrome", note: "Like level, radar, or kayak." },
  { id: "facts:124", prompt: "The & symbol is properly called an ____.", answer: "ampersand", note: "It was once treated as the 27th letter." },
  { id: "facts:125", prompt: "The English word with the most dictionary meanings is ____.", answer: "set", note: "It has hundreds of distinct senses." },
  { id: "facts:126", prompt: "A sentence using all 26 letters is called a ____.", answer: "pangram", note: "The quick brown fox sentence is one." },
  { id: "facts:127", prompt: "The word ketchup came from a word in ____.", answer: "Chinese", alts: ["Hokkien"], note: "It traces to a fermented fish sauce name." },
  { id: "facts:128", prompt: "The word quarantine comes from the word for ____ days.", answer: "forty", alts: ["40"], note: "Ships once waited forty days before landing." },
  { id: "facts:129", prompt: "The shortest complete sentence in English is ____.", answer: "Go", alts: ["go", "Go."], note: "It has an implied subject and a verb." },
  { id: "facts:130", prompt: "The word robot comes from a Czech word for forced ____.", answer: "labor", alts: ["labour", "work"], note: "It debuted in a 1920 play." },
  { id: "facts:131", prompt: "OK may have started as a joke spelling of oll ____.", answer: "korrect", note: "A 19th-century fad for funny misspellings." },
  { id: "facts:132", prompt: "The word salary comes from the Latin for ____.", answer: "salt", note: "Roman pay was linked to this valuable seasoning." },
  { id: "facts:133", prompt: "Rearranging the letters of a word makes an ____.", answer: "anagram", note: "Listen and silent use the same letters." },
  { id: "facts:134", prompt: "A group of larks in flight is called an ____.", answer: "exaltation", note: "An exaltation of larks -- fittingly poetic." },
  { id: "facts:135", prompt: "A group of buzzards resting together is called a ____.", answer: "committee", note: "In flight, though, they become a kettle." },
  { id: "facts:136", prompt: "Camels have ____ eyelids on each eye.", answer: "three", alts: ["3"], note: "The third one sweeps away sand like a wiper." },
  { id: "facts:137", prompt: "An octopus can taste things with its ____.", answer: "arms", alts: ["suckers", "tentacles"], note: "Its suckers carry taste and touch sensors." },
  { id: "facts:138", prompt: "A group of frogs is called an ____.", answer: "army", note: "An army of frogs on the march." },
  { id: "facts:139", prompt: "Some turtles can breathe through their ____.", answer: "butts", alts: ["rear", "cloaca"], note: "Certain turtles absorb oxygen through the cloaca." },
  { id: "facts:140", prompt: "A group of hedgehogs is called an ____.", answer: "array", note: "An array of hedgehogs, though they're mostly solitary." },
];
