import type { Question } from "../types";

export const q1: Question[] = [
  { id: "afterdark:001", prompt: "{target}'s most embarrassing dating-app bio said ____.", answer: "" },
  { id: "afterdark:002", prompt: "The worst pickup line {target} has ever used is ____.", answer: "" },
  { id: "afterdark:003", prompt: "{target}'s biggest ick on a first date is ____.", answer: "" },
  { id: "afterdark:004", prompt: "The celebrity {target} has an unshakeable crush on is ____.", answer: "" },
  { id: "afterdark:005", prompt: "{target}'s most awkward first-kiss story involves ____.", answer: "" },
  { id: "afterdark:006", prompt: "The most scandalous thing in {target}'s search history is ____.", answer: "" },
  { id: "afterdark:007", prompt: "{target} would break their diet for a night out with ____.", answer: "" },
  { id: "afterdark:008", prompt: "The wildest place {target} has ever kissed someone is ____.", answer: "" },
  { id: "afterdark:009", prompt: "{target}'s go-to flirting move is ____.", answer: "" },
  { id: "afterdark:010", prompt: "The most embarrassing thing {target} has done to impress a crush is ____.", answer: "" },
  { id: "afterdark:011", prompt: "{target}'s worst drunk decision involved ____.", answer: "" },
  { id: "afterdark:012", prompt: "The secret {target} would never tell their parents is ____.", answer: "" },
  { id: "afterdark:013", prompt: "{target}'s most-used excuse to leave a bad date is ____.", answer: "" },
  { id: "afterdark:014", prompt: "The thing {target} finds unexpectedly attractive is ____.", answer: "" },
  { id: "afterdark:015", prompt: "{target}'s guilty-pleasure reality dating show is ____.", answer: "" },
  { id: "afterdark:016", prompt: "The last text {target} regretted sending was ____.", answer: "" },
  { id: "afterdark:017", prompt: "{target} would instantly swipe right on ____.", answer: "" },
  { id: "afterdark:018", prompt: "The most embarrassing thing in {target}'s bedroom is ____.", answer: "" },
  { id: "afterdark:019", prompt: "{target}'s secret talent that would win a bar bet is ____.", answer: "" },
  { id: "afterdark:020", prompt: "The wildest thing {target} has done on a dare is ____.", answer: "" },
  { id: "afterdark:021", prompt: "{target}'s biggest turn-off is ____.", answer: "" },
  { id: "afterdark:022", prompt: "The nickname {target}'s partner secretly calls them is ____.", answer: "" },
  { id: "afterdark:023", prompt: "{target}'s most embarrassing karaoke performance was ____.", answer: "" },
  { id: "afterdark:024", prompt: "The thing {target} does that's secretly a cry for attention is ____.", answer: "" },
  { id: "afterdark:025", prompt: "{target} would ghost their date for ____.", answer: "" },
  { id: "afterdark:026", prompt: "The most scandalous rumor about {target} is ____.", answer: "" },
  { id: "afterdark:027", prompt: "{target}'s worst wingman moment involved ____.", answer: "" },
  { id: "afterdark:028", prompt: "The thing {target} pretends they're too classy for is ____.", answer: "" },
  { id: "afterdark:029", prompt: "{target}'s go-to move after too many drinks is ____.", answer: "" },
  { id: "afterdark:030", prompt: "The most embarrassing thing {target} has cried about is ____.", answer: "" },
  { id: "afterdark:031", prompt: "{target}'s secret celebrity hall pass is ____.", answer: "" },
  { id: "afterdark:032", prompt: "The wildest party {target} has ever been to involved ____.", answer: "" },
  { id: "afterdark:033", prompt: "{target}'s most cringe-worthy ex story is ____.", answer: "" },
  { id: "afterdark:034", prompt: "The thing {target} conveniently lies about on first dates is ____.", answer: "" },
  { id: "afterdark:035", prompt: "{target} would do almost anything for a weekend with ____.", answer: "" },
  { id: "afterdark:036", prompt: "The most embarrassing photo of {target} shows them ____.", answer: "" },
  { id: "afterdark:037", prompt: "{target}'s biggest romantic red flag is ____.", answer: "" },
  { id: "afterdark:038", prompt: "The thing {target} snoops through when nobody's home is ____.", answer: "" },
  { id: "afterdark:039", prompt: "{target}'s most awkward run-in with an ex involved ____.", answer: "" },
  { id: "afterdark:040", prompt: "The confession {target} would only make at 2am is ____.", answer: "" },
];
