import type { Question } from "../types";

export const q2: Question[] = [
  { id: "afterdark:041", prompt: "{target}'s most embarrassing bathroom mishap involved ____.", answer: "" },
  { id: "afterdark:042", prompt: "The thing {target} does that's an instant mood-killer is ____.", answer: "" },
  { id: "afterdark:043", prompt: "{target}'s wildest vacation story involves ____.", answer: "" },
  { id: "afterdark:044", prompt: "The most scandalous thing {target} has worn in public is ____.", answer: "" },
  { id: "afterdark:045", prompt: "{target} would trade their best friend for a date with ____.", answer: "" },
  { id: "afterdark:046", prompt: "The secret {target} keeps from their roommates is ____.", answer: "" },
  { id: "afterdark:047", prompt: "{target}'s go-to lie to get out of plans is ____.", answer: "" },
  { id: "afterdark:048", prompt: "The most embarrassing thing {target} has done stone-cold sober is ____.", answer: "" },
  { id: "afterdark:049", prompt: "{target}'s biggest overshare after two drinks is ____.", answer: "" },
  { id: "afterdark:050", prompt: "The thing {target} is weirdly into is ____.", answer: "" },
  { id: "afterdark:051", prompt: "{target}'s most regrettable tattoo idea was ____.", answer: "" },
  { id: "afterdark:052", prompt: "The last thing {target} did that they'd never admit is ____.", answer: "" },
  { id: "afterdark:053", prompt: "{target} would flirt shamelessly with ____.", answer: "" },
  { id: "afterdark:054", prompt: "The most awkward thing {target} has blurted out mid-date is ____.", answer: "" },
  { id: "afterdark:055", prompt: "{target}'s secret dating dealbreaker is ____.", answer: "" },
  { id: "afterdark:056", prompt: "The wildest thing on {target}'s bucket list is ____.", answer: "" },
  { id: "afterdark:057", prompt: "{target}'s most embarrassing gym moment involved ____.", answer: "" },
  { id: "afterdark:058", prompt: "The thing {target} does when they think they're being smooth is ____.", answer: "" },
  { id: "afterdark:059", prompt: "{target}'s worst kiss was ruined by ____.", answer: "" },
  { id: "afterdark:060", prompt: "The most scandalous app on {target}'s phone is ____.", answer: "" },
  { id: "afterdark:061", prompt: "{target} would embarrass themselves for a chance with ____.", answer: "" },
  { id: "afterdark:062", prompt: "The thing {target} secretly loves being complimented on is ____.", answer: "" },
  { id: "afterdark:063", prompt: "{target}'s most cringe text to a crush said ____.", answer: "" },
  { id: "afterdark:064", prompt: "The wildest dare {target} would accept for money is ____.", answer: "" },
  { id: "afterdark:065", prompt: "{target}'s biggest party foul was ____.", answer: "" },
  { id: "afterdark:066", prompt: "The thing {target} frantically hides before guests come over is ____.", answer: "" },
  { id: "afterdark:067", prompt: "{target}'s most embarrassing celebrity crush is ____.", answer: "" },
  { id: "afterdark:068", prompt: "The most awkward place {target} has been recognized is ____.", answer: "" },
  { id: "afterdark:069", prompt: "{target} would happily cancel a date for ____.", answer: "" },
  { id: "afterdark:070", prompt: "The secret hobby {target} would never post online is ____.", answer: "" },
  { id: "afterdark:071", prompt: "{target}'s most awkward morning-after story involves ____.", answer: "" },
  { id: "afterdark:072", prompt: "The thing {target} does that totally ruins the mood is ____.", answer: "" },
  { id: "afterdark:073", prompt: "{target}'s most embarrassing autocorrect to a crush was ____.", answer: "" },
  { id: "afterdark:074", prompt: "The wildest thing {target} has done to win someone over is ____.", answer: "" },
  { id: "afterdark:075", prompt: "{target}'s biggest flirting fail was ____.", answer: "" },
  { id: "afterdark:076", prompt: "The thing {target} pretends to be into just for a date is ____.", answer: "" },
  { id: "afterdark:077", prompt: "{target}'s most scandalous Halloween costume was ____.", answer: "" },
  { id: "afterdark:078", prompt: "The confession {target} would make after three cocktails is ____.", answer: "" },
  { id: "afterdark:079", prompt: "{target} would risk total embarrassment for ____.", answer: "" },
  { id: "afterdark:080", prompt: "The thing {target} secretly practices in the mirror is ____.", answer: "" },
];
