import type { Question } from "../types";

export const q3: Question[] = [
  { id: "afterdark:081", prompt: "{target}'s most awkward group-chat mistake was ____.", answer: "" },
  { id: "afterdark:082", prompt: "The thing {target} does that screams main-character energy is ____.", answer: "" },
  { id: "afterdark:083", prompt: "{target}'s wildest never-have-I-ever confession is ____.", answer: "" },
  { id: "afterdark:084", prompt: "The most embarrassing thing {target} has done for a free drink is ____.", answer: "" },
  { id: "afterdark:085", prompt: "{target}'s go-to move when they want attention is ____.", answer: "" },
  { id: "afterdark:086", prompt: "The secret {target} would only reveal during truth or dare is ____.", answer: "" },
  { id: "afterdark:087", prompt: "{target}'s most cringe-worthy dance-floor moment was ____.", answer: "" },
  { id: "afterdark:088", prompt: "The thing {target} finds irresistibly attractive is ____.", answer: "" },
  { id: "afterdark:089", prompt: "{target}'s worst date-night outfit choice was ____.", answer: "" },
  { id: "afterdark:090", prompt: "The most scandalous thing {target} has done at a wedding is ____.", answer: "" },
  { id: "afterdark:091", prompt: "{target} would sneak out of work early for ____.", answer: "" },
  { id: "afterdark:092", prompt: "The thing {target} lies about to seem cooler is ____.", answer: "" },
  { id: "afterdark:093", prompt: "{target}'s most embarrassing slow-dance memory is ____.", answer: "" },
  { id: "afterdark:094", prompt: "The wildest thing {target} keeps in their nightstand is ____.", answer: "" },
  { id: "afterdark:095", prompt: "{target}'s biggest delete-that-photo moment was ____.", answer: "" },
  { id: "afterdark:096", prompt: "The thing {target} does that's secretly attention-seeking is ____.", answer: "" },
  { id: "afterdark:097", prompt: "{target}'s most awkward flirtation happened at ____.", answer: "" },
  { id: "afterdark:098", prompt: "The confession {target} saves for the group chat is ____.", answer: "" },
  { id: "afterdark:099", prompt: "{target} would embarrass their whole family for ____.", answer: "" },
  { id: "afterdark:100", prompt: "The thing {target} is secretly vain about is ____.", answer: "" },
  { id: "afterdark:101", prompt: "{target}'s most regrettable late-night text said ____.", answer: "" },
  { id: "afterdark:102", prompt: "The wildest rumor {target} ever started was ____.", answer: "" },
  { id: "afterdark:103", prompt: "{target}'s biggest turn-on is ____.", answer: "" },
  { id: "afterdark:104", prompt: "The most scandalous thing {target} has done on vacation is ____.", answer: "" },
  { id: "afterdark:105", prompt: "{target}'s go-to karaoke song to seduce a room is ____.", answer: "" },
  { id: "afterdark:106", prompt: "The thing {target} does that they think is charming is ____.", answer: "" },
  { id: "afterdark:107", prompt: "{target}'s most awkward blind-date story involves ____.", answer: "" },
  { id: "afterdark:108", prompt: "The secret {target} would spill after one more glass of wine is ____.", answer: "" },
  { id: "afterdark:109", prompt: "{target} would ditch us all for a night with ____.", answer: "" },
  { id: "afterdark:110", prompt: "The thing {target} hides in their browser tabs is ____.", answer: "" },
  { id: "afterdark:111", prompt: "{target}'s most embarrassing crush confession was about ____.", answer: "" },
  { id: "afterdark:112", prompt: "The wildest thing {target} would do on a dare for $100 is ____.", answer: "" },
  { id: "afterdark:113", prompt: "{target}'s biggest dating-app disaster involved ____.", answer: "" },
  { id: "afterdark:114", prompt: "The thing {target} secretly wants to be complimented on is ____.", answer: "" },
  { id: "afterdark:115", prompt: "{target}'s most scandalous group-vacation moment was ____.", answer: "" },
  { id: "afterdark:116", prompt: "The confession {target} would only make in the dark is ____.", answer: "" },
  { id: "afterdark:117", prompt: "{target}'s go-to excuse after a bad-date story is ____.", answer: "" },
  { id: "afterdark:118", prompt: "The thing {target} does that's low-key thirsty is ____.", answer: "" },
  { id: "afterdark:119", prompt: "{target}'s most cringe attempt at being smooth was ____.", answer: "" },
  { id: "afterdark:120", prompt: "The wildest secret {target} is keeping right now is ____.", answer: "" },
];
